name: era
description: "Offline AI Desktop Assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  file_picker: ^10.3.2

  provider: ^6.1.5
  http: ^1.5.0

  sqflite_common_ffi: ^2.3.6
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

  flutter_markdown_plus: ^1.0.3
  flutter_highlight: ^0.7.0

  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf